openapi: 3.0.3
info:
  title: Swagger - OpenAPI 3.0
  version: 0.0.1

paths:
  /users/{id}:
    get:
      tags:
        - user
      summary: Get user by id
      operationId: getUserById
      parameters:
        - name: id
          required: true
          in: path
          description: the user id
          schema: 
            type: string
            format: uuid
      responses:
        '200':
          description: User Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

components:
  schemas:
    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
