services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hexagonal
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"